# Include toolbox tasks
include ./.toolbox.mk

# Default image version/tag (override via: make build-image AGH_SYNC_VERSION=...)
AGH_SYNC_VERSION ?= main

# Run go lint against code
lint: tb.golangci-lint
	$(TB_GOLANGCI_LINT) run --fix --build-tags e2e ./...

# Run go mod tidy
tidy:
	go mod tidy

generate: model mocks deepcopy-gen update-e2e-versions docs
deepcopy-gen: tb.controller-gen
	@mkdir -p ./tmp
	@touch ./tmp/deepcopy-gen-boilerplate.go.txt
	$(TB_CONTROLLER_GEN) paths=./internal/types object

docs:
	go run cmd/docs/main.go

.PHONY: docs test test-ci test-e2e test-e2e-external e2e-setup-k8s e2e-stop-k8s update-e2e-versions

# Run tests
test: generate lint test-ci

# Run E2E tests
test-e2e:
	./testdata/e2e/bin/install-chart.sh $(MODE)
	E2E_MODE=$(MODE) go test -v -tags=e2e ./test/e2e/...

# Run E2E tests against an external / IDE-debugged sync process
test-e2e-external:
	E2E_EXTERNAL_SYNC=true E2E_MODE=$(MODE) go test -v -tags=e2e ./test/e2e/...

KIND_CLUSTER_NAME ?= adguardhome-sync-e2e
MODE ?= env
SYNC_ENABLED ?= true

e2e-setup-k8s:
	kind create cluster --name $(KIND_CLUSTER_NAME) --config testdata/e2e/kind.yaml || true
	KIND_CLUSTER_NAME=$(KIND_CLUSTER_NAME) ./testdata/e2e/bin/build-image.sh
	SYNC_ENABLED=$(SYNC_ENABLED) ./testdata/e2e/bin/install-chart.sh $(MODE)

e2e-stop-k8s:
	kind delete cluster --name $(KIND_CLUSTER_NAME)

fuzz:
	 go test -fuzz=FuzzMask -v ./internal/types/ -fuzztime=60s

# Run ci tests
test-ci: mocks tidy
	go test -cover -coverprofile coverage.out.tmp ./...
	grep -v "zz_generated\." coverage.out.tmp > coverage.out
	go tool cover -func=coverage.out

mocks: tb.mockgen
	$(TB_MOCKGEN) -package client -build_constraint "!ignore_autogenerated" -destination internal/mocks/client/zz_generated.mock.go github.com/bakito/adguardhome-sync/internal/client Client
	$(TB_MOCKGEN) -package client -build_constraint "!ignore_autogenerated" -destination internal/mocks/flags/zz_generated.mock.go github.com/bakito/adguardhome-sync/internal/config Flags

release: tb.semver tb.goreleaser tb.syft
	@version=$$($(TB_SEMVER)); \
	git tag -s $$version -m"Release $$version"; \
	git push origin $$version
	PATH=$(TB_LOCALBIN):$${PATH} $(TB_GORELEASER) --clean --parallelism 2

test-release: tb.goreleaser tb.syft
	PATH=$(TB_LOCALBIN):$${PATH} $(TB_GORELEASER) --skip=publish --snapshot --clean --parallelism 2

check-vulnerabilities:
	go run golang.org/x/vuln/cmd/govulncheck@latest -show verbose,color ./...

check_defined = \
    $(strip $(foreach 1,$1, \
        $(call __check_defined,$1,$(strip $(value 2)))))
__check_defined = \
    $(if $(value $1),, \
      $(error Undefined $1$(if $2, ($2))))

build-image:
	$(call check_defined, AGH_SYNC_VERSION)
	docker build \
		--build-arg VERSION=${AGH_SYNC_VERSION} \
		--build-arg BUILD=$(shell date --utc +%Y-%m-%dT%H:%M:%SZ) \
		-t ghcr.io/bakito/adguardhome-sync:${AGH_SYNC_VERSION} \
		.

kind-create:
	kind delete cluster --name $(KIND_CLUSTER_NAME) 2>/dev/null || true
	kind create cluster --name $(KIND_CLUSTER_NAME) --config testdata/e2e/kind.yaml

kind-test:
	@./testdata/e2e/bin/install-chart.sh $(MODE)

# renovate: packageName=AdguardTeam/AdGuardHome
ADGUARD_HOME_VERSION ?= v0.107.79

update-e2e-versions:
	go run cmd/e2e/main.go $(ADGUARD_HOME_VERSION)

model: tb.oapi-codegen
	@mkdir -p tmp
	go run cmd/openapi/main.go $(ADGUARD_HOME_VERSION)
	$(TB_OAPI_CODEGEN) -package model -generate types,client -config .oapi-codegen.yaml tmp/schema.yaml > internal/client/model/zz_generated.model.go

model-diff:
	go run cmd/openapi/main.go $(ADGUARD_HOME_VERSION)
	go run cmd/openapi/main.go
	diff tmp/schema.yaml tmp/schema-master.yaml

zellij:
	zellij -l ./testdata/test-layout.kdl
