name: General Issue
description: Report an issue with your setup
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue report! If you have usage questions, please try the [FAQ](https://github.com/bakito/adguardhome-sync/wiki/FAQ) first.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: adguardhome-sync-version
    attributes:
      label: AdguardHome-Sync Version
      description: What version of adguardhome-sync was running when you discovered this issue?
    validations:
      required: true
  - type: textarea
    id: adguardhome-version
    attributes:
      label: AdguardHome Version
      description: What version of adguardhome was running when you discovered this issue?
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: |
        - How did you configure adguardhome-sync?
        - Please provide your configuration
      render: shell
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant **debug** log output. This will be automatically formatted into code, so no need for backticks.
        Enable debug logs by defining the following environment variable `LOG_LEVEL=debug`.
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will provide more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
