//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package types

import (
	net "net"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdGuardInstance) DeepCopyInto(out *AdGuardInstance) {
	*out = *in
	if in.DHCPServerEnabled != nil {
		in, out := &in.DHCPServerEnabled, &out.DHCPServerEnabled
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdGuardInstance.
func (in *AdGuardInstance) DeepCopy() *AdGuardInstance {
	if in == nil {
		return nil
	}
	out := new(AdGuardInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	in.Origin.DeepCopyInto(&out.Origin)
	if in.Replica != nil {
		in, out := &in.Replica, &out.Replica
		*out = new(AdGuardInstance)
		(*in).DeepCopyInto(*out)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = make([]AdGuardInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.API = in.API
	out.Features = in.Features
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSConfig) DeepCopyInto(out *DNSConfig) {
	*out = *in
	if in.Upstreams != nil {
		in, out := &in.Upstreams, &out.Upstreams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Bootstraps != nil {
		in, out := &in.Bootstraps, &out.Bootstraps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BlockingIPv4 != nil {
		in, out := &in.BlockingIPv4, &out.BlockingIPv4
		*out = make(net.IP, len(*in))
		copy(*out, *in)
	}
	if in.BlockingIPv6 != nil {
		in, out := &in.BlockingIPv6, &out.BlockingIPv6
		*out = make(net.IP, len(*in))
		copy(*out, *in)
	}
	if in.LocalPTRUpstreams != nil {
		in, out := &in.LocalPTRUpstreams, &out.LocalPTRUpstreams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSConfig.
func (in *DNSConfig) DeepCopy() *DNSConfig {
	if in == nil {
		return nil
	}
	out := new(DNSConfig)
	in.DeepCopyInto(out)
	return out
}
