name: e2e tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build:
          - mode: env
            protocol: https
          - mode: file
            protocol: http
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "go.mod"

      - name: Install kind with registry
        uses: bakito/kind-with-registry-action@b13dc5fd599a5c774e7ca721d6e7a34f7269d2d8 # v1.0.1
        with:
          kind_cluster_name: adguardhome-sync-e2e

      - name: Build image
        run: ./testdata/e2e/bin/build-image.sh

      - name: Install Helm Chart
        run: ./testdata/e2e/bin/install-chart.sh ${{ matrix.build.mode }}

      - name: Run Go E2E Tests
        env:
          E2E_TARGET: k8s
          E2E_MODE: ${{ matrix.build.mode }}
          E2E_PROTOCOL: ${{ matrix.build.protocol }}
        run: go test -v -tags=e2e ./test/e2e/...
