# managed by https://github.com/bakito/github-files sync action
name: govulncheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule: # daily at 03:33 UTC
    - cron: "33 03 * * *"
  workflow_dispatch:

permissions:
  contents: read
jobs:
  govulncheck:
    name: Check Vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Run code generation if available
        run: |
          if make -n generate > /dev/null 2>&1; then
            make generate
          fi

      - name: Check vulnerabilities
        run: go run golang.org/x/vuln/cmd/govulncheck@latest -show verbose,color ./...
