name: docker-image

on:
  push:
    branches:
      - container-tests

jobs:
  test:
    #needs: image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create kind cluster
        uses: helm/kind-action@v1.3.0
      - name: Start adguardhome instances
        run: |
          kubectl create configmap origin-conf -n default --from-file testdata/e2e/AdGuardHome.yaml
          kubectl apply -n default -f testdata/e2e/agh
          kubectl wait -n default --for condition=Ready pod/adguardhome-origin --timeout=30s
          kubectl wait -n default --for condition=Ready pod/adguardhome-replica --timeout=30s
      - name: Start adguardhome-sync
        run: |
          kubectl create configmap sync-conf -n default --from-env-file=testdata/e2e/sync-conf.properties
          kubectl apply -n default -f testdata/e2e/job-adguardhome-sync.yaml
          kubectl wait --for=condition=complete job/adguardhome-sync
      - name: Show Logs
        run: |
          echo adguardhome-sync
          kubectl logs adguardhome-sync
          echo adguardhome-replica
          kubectl logs adguardhome-replica
