name: Scan GitHub Release with VirusTotal

on:
  release:
    types: [released]

jobs:
  scan_release:
    runs-on: ubuntu-latest

    steps:
      - name: Analyze Build Assets
        uses: bakito/virustotal-action@f27c5bc29fedcfc124c12e1c37a91bfb0a20276f # v1.0.3
        with:
          release_name: ${{github.event.release.tag_name}}
          vt_api_key: ${{secrets.VT_API_KEY}}